### ISSUE TITLE
Avoid commonly used layout name 

### ISSUE THREAD

**Issue by minkiapps** [bluesource/ChoiceSDK#15]
Version Choicesdk-maps 0.2

I realise that an internal layout named `fragment_map` is used. Generally it is bad practise if an library internal layout is named in a very common way. Library caller can easily have to same layout name and this would cause runtime conflict, where the library would use the layout of the consumer instead of it's own.

I recommend to add at least a prefix to avoid naming conflicts, like `choice_fragment_map`.
See also this [SO post](https://stackoverflow.com/a/16351116/13782111).

**Comment by officebluesource** [comment]
Issue should be fixed with [version 0.3.0](https://github.com/bluesource/ChoiceSDK/releases/tag/0.3.0).
