### ISSUE TITLE
MapFragment should have an empty constructor

### ISSUE THREAD

**Issue by minkiapps** [bluesource/ChoiceSDK#16]
Version Choicesdk-maps 0.2

`at.bluesource.choicesdk.maps.common.MapFragment` should have an empty constructor, which is required by Android Fragment framework, else wise this could lead to crashes from onRestoreInstanceState etc.

I propose to add a JvmOverloads annotation to constructor like this: `@JvmOverloads constructor(options: MapOptions? = null)`

**Comment by officebluesource** [comment]
Issue should be fixed with [version 0.3.0](https://github.com/bluesource/ChoiceSDK/releases/tag/0.3.0).
