### ISSUE TITLE
Unable to use IDE Layout Inspector when MapFragment is in play

### ISSUE THREAD

**Issue by minkiapps** [bluesource/ChoiceSDK#17]
Version Choicesdk-maps 0.2

I realised that as soon as the `at.bluesource.choicesdk.maps.common.MapFragment` is used, the layout inspector of Android Studio would cause app to crash. It makes the user impossible to inspect the layout hierarchy while using Choicemap library. 

Just try to use the layout inspector in your demo MapActivity to reproduce the crash.

**Comment by officebluesource** [comment]
Issue should be fixed with [version 0.3.0](https://github.com/bluesource/ChoiceSDK/releases/tag/0.3.0).
