### ISSUE TITLE
Not a issue but a Question 

### ISSUE THREAD

**Issue by Andre305** [bluesource/ChoiceSDK#18]
I'm fairly new to all this. I'm using cordova and have a webapp. How do I implement this into cordova to create my webbapp for the new huawei devices? Have anyone tried it before? I'm not using Android Studio to create my app.

**Comment by Queatz** [comment]
You wouldn't use this for a webapp...as far as I can tell.  I've used it in a native Android app.

**Comment by Andre305** [comment]
Thanks for the reply
So i can convert the cordova created android project to hms using android studio?

**Comment by Queatz** [comment]
Not sure, because Cordova is not native Android...you might be looking for something more like this: https://github.com/HMS-Core/hms-cordova-plugin

**Comment by Andre305** [comment]
Thank you very much. your a life saver
