### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chitgoks** [bluesource/ChoiceSDK#3]
Possible to support google map util classes?

**Comment by BsBrabi** [comment]
Which features do you want to use from the Google Maps Utility Library?

In general, almost all features of the Utility Library are not available in HMS Map Kit, therefore it is difficult to provide a clean interface in our Choice SDK which can be equally used on GMS and HMS devices.

I think for most features you would need custom GMS/HMS implementations anyway. For things like marker clustering we would need to implement custom interfaces and converters to use classes like `ClusterManager`, whereas HMS Map Kit only provides us with the possibility to enable clustering via `setMarkersClustering(true)`.

However, most features can be used by providing a `GoogleMap` object to e.g. `ClusterManager` or `KmlLayer`.

So the best solution to use the Utility Library features is by converting our `Map` object to `com.google.android.gms.maps.GoogleMap`, so I think we can implement something like this to provide you with a `GoogleMap` object:
`fun at.bluesource.choicesdk.maps.common.Map.toGoogleMap(): com.google.android.gms.maps.GoogleMap`

**Comment by chitgoks** [comment]
i see. that could work

**Comment by bluesource** [comment]
Today we will release a new version of ChoiceSDK (v0.1.4), which contains this feature request. Please also refer to the updated Map documentation.
