### ISSUE TITLE
choiceSDK and HMS Toolkit Convertor

### ISSUE THREAD

**Issue by tomgu1991** [bluesource/ChoiceSDK#4]
HI,

There is a tool named HMS Toolkit, which is developed by Huawei.

The Convertor component of HMS Toolkit can automatically help developer wrap hms and gms api.

The link is here:https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/convertor-0000001050147221

Is ChoiceSDK relative to this toolkit?

Thansk!

**Comment by BsBrabi** [comment]
ChoiceSDK is not related to HMS Toolkit Converter.

HMS Toolkit Converter is a code conversion tool provided by Huawei, whereas ChoiceSDK is a third-party open-source library that aims to wrap similar functionalities from GMS and HMS to one common interface.
