### ISSUE TITLE
at.bluesource.choicesdk.location.factory: Missing underlying GMS/HMS API.

### ISSUE THREAD

**Issue by sevriugin** [bluesource/ChoiceSDK#7]
Hi, guys I've got a problem with my App published in Huawei Gallery: Pixel 3 XL / Android 9

Unable to start activity ComponentInfo{co.nubee.android/co.nubee.android.MapsActivity}: java.lang.UnsupportedOperationException: Missing underlying GMS/HMS API.

at.bluesource.choicesdk.location.factory.FusedLocationProviderFactory$Companion.getFusedLocationProviderClient (FusedLocationProviderFactory.kt:67)
co.nubee.android.MapsActivity.onCreate (MapsActivity.kt:514)

```
// MapsActivity.kt: 
override fun onCreate(savedInstanceState: Bundle?) {
// Line 514
       client = FusedLocationProviderFactory.getFusedLocationProviderClient(this)
// ...
}
```

**Comment by BsBrabi** [comment]
It looks like GMS is not available on this device, as `GoogleApiAvailability.isGooglePlayServicesAvailable` returns no successful connection result.

Please refer to the [Google documentation](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#isGooglePlayServicesAvailable(android.content.Context)), unfortunately we do not output the actual connection result to the logs yet.

Do you have this problem only on this specific device, or does it happen on other devices too?
