### ISSUE TITLE
HMS or GMS priority selection

### ISSUE THREAD

**Issue by ClarkXP** [bluesource/ChoiceSDK#8]
For testing in devices with both services availables (ex. P30 Pro), can be defined which services be loaded? I need to test the map example and haven't available a device HMS-only

**Comment by bluesource** [comment]
We just released version 0.2.0 of the SDK, which includes this feature request.

Now you can set the priority in which order the service availability is checked. Please refer to the [readme](https://github.com/bluesource/ChoiceSDK#initialization) for documentation.
